# Site settings
title: DUO FITNESS
email: givespower.health@gmail.com

# Development Settings
baseurl: "/"
url: "http://localhost:4000"

include: ["_pages"]
logo: 'img/logo/duo-logo-yellow.jpg'

line_url: https://lin.ee/Umt7lpD
instagram_url: https://www.instagram.com/duofitness.health?igsh=dWwzemIxcTM1NXc0
address_url: https://maps.app.goo.gl/V34db2nEdmVg2K6t7

# Developer settings
developer_name: Crystal Chang
